# Generated by Django 3.0.2 on 2020-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('TECH', 'Technology'), ('HE', 'Health'), ('GR', 'General')], default='GR', max_length=4),
        ),
    ]
