# Generated by Django 3.0.2 on 2020-01-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deleted',
            new_name='approved',
        ),
    ]
