# Generated by Django 3.0.2 on 2020-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200110_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moreInfo',
            field=models.URLField(default=''),
        ),
    ]
